### ISSUE TITLE
Wrong statement

### ISSUE THREAD

**Issue by Dabolus** [ecthros/uncaptcha2#11]
> ⚠️ This code works on the most recent version of ReCaptcha. Only use on sites you control for educational purposes. ⚠️

You project is great, but it only works with reCAPTCHA v2. After the traditional reCAPTCHA v2, the Invisible reCAPTCHA first and the reCAPTCHA v3 later on came out, which don't need any user interaction. I think you should specify that this doesn't actually work with the most recent version of reCAPTCHA, but only with v2.

**Comment by ecthros** [comment]
Thanks for this, I'll make the change.
