### ISSUE TITLE
"Your computer or network may be sending automated queries."

### ISSUE THREAD

**Issue by ghost** [ecthros/uncaptcha2#13]
Can't get this workaround to work if reCAPTCHA spits out this error - I'm unable to confirm the exact variables that cause this, perhaps you guys could help shed some light?

**Comment by ecthros** [comment]
Thanks for reaching out!

I haven't tested this recently, and I'm not sure if they've changed anything around. We're not trying to keep this an updated repository - we don't want just anyone to have the ability to beat captchas.

I'll have some time in a couple weeks, I might try taking a look then.

**Comment by azamet90** [comment]
> Thanks for reaching out!
> 
> I haven't tested this recently, and I'm not sure if they've changed anything around. We're not trying to keep this an updated repository - we don't want just anyone to have the ability to beat captchas.
> 
> I'll have some time in a couple weeks, I might try taking a look then.

couple of weeks turns to a year sir any news?
