### ISSUE TITLE
uncaptcha2 can it run on mac

### ISSUE THREAD

**Issue by 0c0c0f** [ecthros/uncaptcha2#2]
uncaptcha2 can it run on mac

**Comment by Eastkap** [comment]
Did you try it?

**Comment by ecthros** [comment]
As long as you get the dependencies installed, I don't see any reason why it wouldn't work on a Mac. Have a nice day!

**Comment by 0c0c0f** [comment]
Removing old files...
Opening Firefox
convert: unable to open image 'xwd:-': No such file or directory @ error/blob.c/OpenBlob/3492.
convert: no decode delegate for this image format `' @ error/constitute.c/ReadImage/556.
convert: no images defined `txt:-' @ error/convert.c/ConvertImageCommand/3300.
