### ISSUE TITLE
Your computer or network may be sending automated queries...

### ISSUE THREAD

**Issue by ayancey** [ecthros/uncaptcha2#3]

**Comment by Eastkap** [comment]
Use proxies / change ip and try again. Seems like you used this too much

**Comment by ecthros** [comment]
Depending on how your browser is configured, reCaptcha might think you're a bot. If that happens, you either need to wait some time or get a new IP address. I have had this run for 8+ hours at a time so it is possible to set everything up correctly without changing IPs.
